In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [3]:
array2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(array2.shape) 

(15,)


In [4]:
a = array2.reshape(3,5) 
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [5]:
print("shape: ",a.shape) 

print("dimension: ",a.ndim)

print("data type: ",a.dtype.name)
print("size: ",a.size) 
                       
print("type",type(a))

shape:  (3, 5)
dimension:  2
data type:  int64
size:  15
type <class 'numpy.ndarray'>


In [10]:
array3= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array3)

print(array3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [13]:
zeros= np.zeros((3,4))
zeros[0,0]=5
print(zeros)

np.ones((3,4))

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.empty((4,5))

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

In [17]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
a= np.linspace(0,10,20) 
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [19]:
a= np.array([1,2,3])
b= np.array([4,5,6]) 

print(a+b) 
print(a-b) 
print(a**2) 

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [21]:
liste = [1,2,3,4]

array = np.array([5,6,7,8])
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [23]:
array = np.array(liste)
print(array)


[1 2 3 4]


In [24]:
liste2 = list(array) 
print(liste2)

[1, 2, 3, 4]


In [25]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [29]:
b=a

c=a

b[0]=5 
print(a,b,c)
d = a.copy()

[5 2 3] [5 2 3] [5 2 3]


In [30]:
a= np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [31]:
print(a[0])

1


In [32]:
print(a[0:4])

[1 2 3 4]


In [33]:
reverse_array = a[::-1] 
print(reverse_array)

[7 6 5 4 3 2 1]


In [34]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [35]:
print(b[1,1])

print(b[:,1])

print(b[1,:])

print(b[1,1:4])

print(b[-1,:])

print(b[:,-1])

7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [36]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]]) #3*3'lük array oluşturuldu.
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
a = array.ravel()
print(a)

[1 2 3 4 5 6 7 8 9]


In [38]:
array2 = a.reshape(3,3) 
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
array_transpose = array2.T
print(array_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [40]:
array3 = np.array([[1,2],[3,4],[5,6]])
print(array3)

[[1 2]
 [3 4]
 [5 6]]


In [41]:
array3.resize((2,3))
print(array3)

[[1 2 3]
 [4 5 6]]
